spring.application.name=devTrack1

# Database URL
spring.datasource.url= ${url}

# Credentials
spring.datasource.username= ${username}
spring.datasource.password= ${password}
gemini.api.key=${GEMINI_API_KEY}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional (helpful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true